### ISSUE TITLE
Using the openapi-generator-go for the github api (api.github.com) does not work

### ISSUE THREAD

**Issue by RemkoMolier** [contiamo/openapi-generator-go#100]
whilst using the openapi-generator-go to generate the model for the [github api](https://github.com/github/rest-api-description/raw/main/descriptions/api.github.com/api.github.com.yaml) I ran into a few issues:

- Using the plain basename of the reference as GoType does not always work (pkg/generators/models/go_type_from_ref.go)
- Generated comments that run over multiple lines need to be formatted properly (pkg/generators/models/templates/oneof.gotpl)
- Names that start with a + or -, even when not good practice, indicate "plus" or "minus"

I'll fix these issues one by one and send over PRs for you to check and incorporate if ok.

Kind regards,

Remko Molier

**Comment by LucasRoesler** [comment]
This should be resolved now in #104 and the latest release v2.0.3
