### ISSUE TITLE
AdditionalProperties true by default

### ISSUE THREAD

**Issue by injeniero** [contiamo/openapi-generator-go#139]
Hi @LucasRoesler!

While I was working on the issue #136 I found that starting from OpenAPI 3.0.2 they clarified that [additionalProperties is true by default](https://spec.openapis.org/oas/v3.0.3#schema-object:~:text=additionalProperties%20%2D%20Value%20can%20be%20boolean%20or%20object.%20Inline%20or%20referenced%20schema%20MUST%20be%20of%20a%20Schema%20Object%20and%20not%20a%20standard%20JSON%20Schema.%20Consistent%20with%20JSON%20Schema%2C%20additionalProperties%20defaults%20to%20true). 

The current implementation does not follow this. So wanted to start a discussion on this, should this be fixed?

**Comment by injeniero** [comment]
I personally don't like the idea of having to set `additionalProperties: false` on every schema. Feels like an odd direction to follow, but it is the standard. Not sure how many generators respect this. 

I would be fine not following it and explain that in the documentation. I think the current implementation is as follow:

### Object with no properties
Here it assumes `additionalProperties: true`
```YAML
type: object
```

```Go
map[string]interface{}
```

### Object with additionalProperties set to true|{}
This is just like not setting it
```YAML
type: object
additionalProperties: true|{}
```

```Go
map[string]interface{}
```

### Object with properties
It assumes `additionalProperties: false`
```YAML
type: object
properties:
  field1:
    type: string
```

```Go
struct {
  Field1 string
}
```

### Object with properties and additionalProperties set to true|{}
```YAML
type: object
properties:
  field1:
    type: string
additionalProperties: true|{}
```

```Go
struct {
  Field1 string
  AdditionalProperties map[string]interface{}
}
```

**Comment by LucasRoesler** [comment]
I very much agree with you, this is a weird default and would be very annoying to model and use in Go. I would rather document this as an exception.

**Comment by LucasRoesler** [comment]
I guess we could also consider a flag `--strict` to toggle this behavior. 

But it is definitely not something I would use. When I am designing an API I never assume additional properties, I design the fields I want and only rarely allow additional properties when the application needs it.

**Comment by injeniero** [comment]
Great, I was also thinking on the "--strict" flag, but that could be something for the future.
