### ISSUE TITLE
Cannot build inside docker image ubuntu/golang

### ISSUE THREAD

**Issue by shinnokdisengir** [contiamo/openapi-generator-go#71]
Hi,
I need to build the generator inside a container, because there are no builded packages (I think..)

Here is a slice of the "prepare to build" Dockerfile

```
RUN apt update
RUN apt install -yq \
    build-essential \
    golang \
    docker.io
RUN apt clean

RUN mkdir -p $GENERATOR_SRC_PATH
RUN git clone https://github.com/contiamo/openapi-generator-go $GENERATOR_SRC_PATH

WORKDIR $GENERATOR_SRC_PATH

COPY ./Makefile .

ENTRYPOINT make && cp ./bin/ build
```

and after builded it, I try to run:

```
docker run \
    -it \
    --rm \
    --privileged \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v $CURRENT_PATH/generator:/build \
   prepare-to-build:dev
```

BUT your makefile doesn't link well the _binary_ step, because the command `make binary` is used after `docker run`. 
`make: *** No rule to make target 'binary'.  Stop.`

Could you publish builded releases? Or help me to resolve this issue? I'm so sad, because your project is "the best" openapi-generator for golang that I've ever seen, it is the only that manages validation

Thanks,
G.

**Comment by LucasRoesler** [comment]
Thanks for letting us know. 

Actually, that Makefile needs a quite a bit of cleanup.  

To get you unblocked right away, I would recommend just using `make binary` instead of just `make`.


```dockerfile
RUN apt update
RUN apt install -yq \
    build-essential \
    golang
RUN apt clean

RUN mkdir -p $GENERATOR_SRC_PATH
RUN git clone https://github.com/contiamo/openapi-generator-go $GENERATOR_SRC_PATH

WORKDIR $GENERATOR_SRC_PATH

ENTRYPOINT make bindary && cp ./bin/ build
```

I am not sure exactly what you are trying to do? Just build/install the binary? The `ENTRYPOINT` you have is a bit unexpected.

Since you are generating Go code, I assume you have go installed already, so I would just use 

```sh
go install github.com/contiamo/openapi-generator-go/cmd/openapi-generator-go@v0.14.2
```

We also use and recommend this project https://github.com/bwplotka/bingo for managing Go based build tools.

I will try to quickly update the repo with both prebuilt binaries on on the releases and a docker image in GHCR.

**Comment by shinnokdisengir** [comment]
Ahhh wonderful! Using `go install` it works fine. I hadn't knew that could works in this repo, Makefile has distracted me, I had understood only `make` can does the job.
Fine, and thanks to suggest me how to change a Dockerfile.

**Comment by LucasRoesler** [comment]
@shinnokdisengir i just updated the release flow, so you can pull a pre-built docker image from the Github Container Registry https://github.com/contiamo/openapi-generator-go/pkgs/container/openapi-generator-go

It as the `openapi-generate-go` binary installed in `/`.

Additionally, there are now pre-built binaries attached to the releases, so you can curl from there as well https://github.com/contiamo/openapi-generator-go/releases/tag/v0.15.0

Of course, the `go install` will continue to work just as before. So you do not have to make any changes.

**Comment by shinnokdisengir** [comment]
thank u very much! 🔝
