### ISSUE TITLE
Use *bool if property is settable

### ISSUE THREAD

**Issue by komex** [contiamo/openapi-generator-go#80]
If OpenAPI has object with optional bool property, there is no way to differentiate `false` value and no value.

I propose to fix [models.go](pkg/generators/models/models.go) with this changes after `spec` variable declaration (line 504):

```go
if spec.GoType == "bool" && !spec.IsRequired && !prop.Value.ReadOnly {
	spec.GoType = "*bool"
}
```

How this works: If type is boolean and field is not required and not read only, we change type to bool pointer. This fix make us able to differentiate `false` and no value.

**Comment by LucasRoesler** [comment]
Hi @komex thanks for using the project and for the suggestion. 

I think you want to use the `nullable: true` property here instead. It has the same effect and a clear meaning when you read the api spec you can immediately see that is is 3-state boolean: `null`, `true`, `false`

**Comment by komex** [comment]
Hi, @LucasRoesler. My bad, your solution works perfectly. Thank.
