### ISSUE TITLE
Non-required Properties that are represented as struct types with `omitempty` should be pointers

### ISSUE THREAD

**Issue by brianV** [contiamo/openapi-generator-go#90]
Hello!

In order for `json.Marshal()` to properly apply to `omitempty` tag and omit properties that contain structs, the property must actually be a pointer to the struct type. However, the generated models contain struct properties directly rather than via pointers.

Here's an example showing the difference when Marshaling Go structs into JSON with & without pointers for the struct properties carrying `omitempty`:

```
package main

import (
	"encoding/json"
	"fmt"
)

type ObjectNoPointer struct {
	Property Property `json:",omitempty"`
}

type ObjectPointer struct {
	Property *Property `json:",omitempty"`
}

type Property struct {
	Key   string
	Value string
}

func main() {
	a := ObjectNoPointer{}
	b := ObjectPointer{}

	resultA, _ := json.Marshal(a)
	resultB, _ := json.Marshal(b)

	fmt.Println("No Pointer:" + string(resultA))
	fmt.Println("Pointer:" + string(resultB))
}
```

The example above can also be viewed at https://go.dev/play/p/pl9hl9Z72e1

**Comment by LucasRoesler** [comment]
You should get a point if you set the field to be nullable. I fully understand how the marshalling works, but is that example 

```go
type ObjectNoPointer struct {
	Property Property `json:",omitempty"`
}
```

Currently being generated by the package? I would be best if we had an example with a minimal schema file, the currently generated Go, and the an example of the desired Go.

**Comment by brianV** [comment]
Sure.

Here's a simple OpenAPI definition that defines an `Item` object type with a property that contains an non-required `OptionalItem` type in a field called `other_item`:
 
[openapi.txt](https://github.com/contiamo/openapi-generator-go/files/10841201/openapi.txt)

Here's the generated struct generated for the `Item` type:

```go
// Item is an object.
type Item struct {
	// Name:
	Name string `json:"name" mapstructure:"name"`
	// OtherItem:
	OtherItem OptionalItem `json:"other_item,omitempty" mapstructure:"other_item,omitempty"`
}
```

and here's what I expect:

```go
// Item is an object.
type Item struct {
	// Name:
	Name string `json:"name" mapstructure:"name"`
	// OtherItem:
	OtherItem *OptionalItem `json:"other_item,omitempty" mapstructure:"other_item,omitempty"`
}```


The reason being that an property that is *not* required but also *not* explicitly nullable can have two valid representations in the JSON:

1. The property is present, and is valid (ie, `OtherItem` is present and contains a valid `OptionalItem` object)
2. The property is not present (ie, `OtherItem` is not present in the generated JSON).

Currently, the first is doable with the generated Go type. However, the second requires the Go property to be a pointer type in combination with `omitempty` so that `json.Marshal()` omits the property from the generated JSON.

**Comment by brianV** [comment]
PR #91 created to address this.
