### ISSUE TITLE
allOf with deep relationships does not work consistently

### ISSUE THREAD

**Issue by injeniero** [contiamo/openapi-generator-go#94]
The oneOf resolution depends on the sort order of the entities to work properly.

This hierarchy works ok because they are in sort order: `UserEntity -> UpdatableEntity -> BaseEntity`, but this one fails: `OrgEntity -> UpdatableEntity -> BaseEntity`.

I think it is a defect to depend on the sort order for this to work.

The fix is to add `right = resolveAllOf(right, passed)` next to: 
 https://github.com/contiamo/openapi-generator-go/blob/56c67ab16713c7ade8352748f772b775704cf86b/pkg/generators/models/models.go#L448

But that breaks a test case.

**Comment by LucasRoesler** [comment]
I dont' fully understand, can you provide a sample OpenAPI spec that reproduces the bug?

**Comment by injeniero** [comment]
Sure:

```yaml
openapi: 3.0.0
info:
  version: 0.1.0
  title: Test

components:
  schemas:
    BaseEntity:
      description: Contains shared properties for all the entities
      type: object
      required:
        - id
        - name
        - type
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string

    UpdatableEntity:
      description: An entity that can be updated.
      allOf:
        - $ref: '#/components/schemas/BaseEntity'
        - type: object
          required:
            - update_ts
          properties:
            update_ts:
              type: integer


    OrgEntity:
      description: An organization
      allOf:
        - $ref: '#/components/schemas/UpdatableEntity'
        - type: object
          required:
            - email
          properties:
            email:
              type: string
              format: email

```

**Comment by injeniero** [comment]
@LucasRoesler did you have a chance to take a look at this?

**Comment by LucasRoesler** [comment]
I totally missed the notification from your previous comment, i am hoping to take a look this weekend.

**Comment by LucasRoesler** [comment]
@injeniero take a look at #95 it should fix the issue, i used the spec you shared above as the new test case.

**Comment by injeniero** [comment]
This is great, thanks so much for looking into this!! I was reviewing your PR and I left a comment on yours.
